base = "/"
favicon = "true"

[style]
theme = "system-preference"
cover = "center"
content = "left"

[profile]
name = "Moul"
bio = "The minimalist publishing tool for photographers"

[social]
twitter = ""
github = "moulco"
instagram = "moul.co"

[content]
title = "Lorem ipsum â€” dolor sit amet, consectetur adipiscing elit"
tags = ["Adventure", "Landscape"]
description = """
Praesent non augue tempus, bibendum sem eu, molestie magna. Maecenas et ligula a libero ullamcorper sollicitudin. Duis aliquet sem dapibus, semper urna in, tempus dolor.
"""

[section.1]
title = "Praesent non augue tempus, bibendum sem eu, molestie magna. Maecenas et ligula a libero ullamcorper sollicitudin."
description = """
Aenean in leo massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut malesuada, ante vel gravida vulputate, eros sapien finibus arcu, a elementum quam massa in felis. Maecenas egestas vestibulum nisl, quis interdum felis pretium vel. Aenean sed fringilla dolor, vel commodo erat.

Curabitur pulvinar blandit purus, in convallis urna congue vitae. Curabitur consectetur lectus nec libero varius volutpat sed vel ligula.

Vivamus eget mauris at lorem hendrerit facilisis. Nulla cursus venenatis felis eget dictum. Mauris mattis varius mauris id ornare. Aliquam nec euismod lorem, at volutpat lorem.
"""
[section.2]
title = "Duis aliquet sem dapibus, semper urna in, tempus dolor"
description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in leo massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut malesuada, ante vel gravida vulputate, eros sapien finibus arcu, a elementum quam massa in felis.

Mauris mattis varius mauris id ornare. Aliquam nec euismod lorem, at volutpat lorem.
"""
[section.3]
title = "Curabitur pulvinar blandit purus, in convallis urna congue vitae"
description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean in leo massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut malesuada, ante vel gravida vulputate, eros sapien finibus arcu, a elementum quam massa in felis. Maecenas egestas vestibulum nisl, quis interdum felis pretium vel. Aenean sed fringilla dolor, vel commodo erat.
"""